### ISSUE TITLE
缓存文件清除问题

### ISSUE THREAD

**Issue by petezhang** [youzan/fast-uglifyjs-plugin#11]
使用插件build过程中产生了大量的缓存map文件，但是插件好像没有提供清理无用缓存文件的功能，这会导致缓存文件越来越大

**Comment by keller35** [comment]
是的，原来对无用的js缓存文件有清除操作，后来增加了map支持就没有了。
这里需要一个pr来做清理map缓存的操作。

**Comment by keller35** [comment]
@petezhang 问题已修复，更新包版本到`0.3.0`即可。
